In [2]:
# 리스트 만들기
mylist <- list(name='kim', quiz=c(50,40,30), score=c(80,90))
mylist

$name
[1] "kim"

$quiz
[1] 50 40 30

$score
[1] 80 90

In [3]:
print(mylist)

$name
[1] "kim"

$quiz
[1] 50 40 30

$score
[1] 80 90



In [ ]:
mylist$quiz
mylist$score[2]

[1] 50 40 30

[1] 90

In [8]:
msg = c("unlist함수를 적용하면, 리스트에 입력된 순서대로 벡터의 원소가 됩니다. ",
        "문자형만 있는 경우 factor로 반환됩니다.",
        "The unlist R function converts a list to a single vector." )
msg

[1] "unlist함수를 적용하면, 리스트에 입력된 순서대로 벡터의 원소가 됩니다. "
[2] "문자형만 있는 경우 factor로 반환됩니다."                               
[3] "The unlist R function converts a list to a single vector."

In [9]:
strings <- strsplit(msg, " ")
strings

[[1]]
[1] "unlist함수를" "적용하면,"    "리스트에"     "입력된"       "순서대로"    
[6] "벡터의"       "원소가"       "됩니다."     

[[2]]
[1] "문자형만"    "있는"        "경우"        "factor로"    "반환됩니다."

[[3]]
 [1] "The"      "unlist"   "R"        "function" "converts" "a"       
 [7] "list"     "to"       "a"        "single"   "vector."

In [11]:
unlist(strings)

[1] "unlist함수를" "적용하면,"    "리스트에"     "입력된"       "순서대로"    
 [6] "벡터의"       "원소가"       "됩니다."      "문자형만"     "있는"        
[11] "경우"         "factor로"     "반환됩니다."  "The"          "unlist"      
[16] "R"            "function"     "converts"     "a"            "list"        
[21] "to"           "a"            "single"       "vector."

In [12]:
m <- matrix(1:20, 4, 5)
m

[,1] [,2] [,3] [,4] [,5]
[1,] 1    5     9   13   17  
[2,] 2    6    10   14   18  
[3,] 3    7    11   15   19  
[4,] 4    8    12   16   20

In [13]:
m_df <- as.data.frame(m)
m_df

V1 V2 V3 V4 V5
1 1  5   9 13 17
2 2  6  10 14 18
3 3  7  11 15 19
4 4  8  12 16 20

In [16]:
apply(m, 2, sum)
apply(m, 1, sum)
apply(m, 2, max)

[1] 10 26 42 58 74

[1] 45 50 55 60

[1]  4  8 12 16 20

In [17]:
m1 <- m[1:2, ]
m1

[,1] [,2] [,3] [,4] [,5]
[1,] 1    5     9   13   17  
[2,] 2    6    10   14   18

In [18]:
m2 <- m[3:4, ]
m2

[,1] [,2] [,3] [,4] [,5]
[1,] 3    7    11   15   19  
[2,] 4    8    12   16   20

In [19]:
rbind(m1, m1)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    5     9   13   17  
[2,] 2    6    10   14   18  
[3,] 1    5     9   13   17  
[4,] 2    6    10   14   18

In [20]:
cbind(m1, m1)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 1    5     9   13   17   1    5     9   13   17   
[2,] 2    6    10   14   18   2    6    10   14   18

In [21]:
mtcars

mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4           21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag       21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4   
Datsun 710          22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive      21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2   
Valiant             18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1   
Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4   
Merc 240D           24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2   
Merc 230            22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2   
Merc 280            19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4   
Merc 280C           17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4   
Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3   
Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3   
Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3   
Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4   
Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4   
Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4   
Fiat 128            32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1   
Honda Civic         30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2   
Toyota Corolla      33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1   
Toyota Corona       21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1   
Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2   
AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2   
Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4   
Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2   
Fiat X1-9           27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1   
Porsche 914-2       26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2   
Lotus Europa        30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2   
Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4   
Ferrari Dino        19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6   
Maserati Bora       15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8   
Volvo 142E          21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

In [22]:
mycars <- mtcars[c(1,4,6)]
head(mycars)

mpg  hp  wt   
Mazda RX4         21.0 110 2.620
Mazda RX4 Wag     21.0 110 2.875
Datsun 710        22.8  93 2.320
Hornet 4 Drive    21.4 110 3.215
Hornet Sportabout 18.7 175 3.440
Valiant           18.1 105 3.460

In [23]:
summary(mtcars)

      mpg             cyl             disp             hp       
 Min.   :10.40   Min.   :4.000   Min.   : 71.1   Min.   : 52.0  
 1st Qu.:15.43   1st Qu.:4.000   1st Qu.:120.8   1st Qu.: 96.5  
 Median :19.20   Median :6.000   Median :196.3   Median :123.0  
 Mean   :20.09   Mean   :6.188   Mean   :230.7   Mean   :146.7  
 3rd Qu.:22.80   3rd Qu.:8.000   3rd Qu.:326.0   3rd Qu.:180.0  
 Max.   :33.90   Max.   :8.000   Max.   :472.0   Max.   :335.0  
      drat             wt             qsec             vs        
 Min.   :2.760   Min.   :1.513   Min.   :14.50   Min.   :0.0000  
 1st Qu.:3.080   1st Qu.:2.581   1st Qu.:16.89   1st Qu.:0.0000  
 Median :3.695   Median :3.325   Median :17.71   Median :0.0000  
 Mean   :3.597   Mean   :3.217   Mean   :17.85   Mean   :0.4375  
 3rd Qu.:3.920   3rd Qu.:3.610   3rd Qu.:18.90   3rd Qu.:1.0000  
 Max.   :4.930   Max.   :5.424   Max.   :22.90   Max.   :1.0000  
       am              gear            carb      
 Min.   :0.0000   Min.   :3.000  

In [27]:
avg <- round(apply(mycars, 2, mean),2)
print(avg)

   mpg     hp     wt 
 20.09 146.69   3.22 


In [32]:
subset(mtcars, mpg > 30 & mpg < 32, select=c(mpg, cyl, wt))

mpg  cyl wt   
Honda Civic  30.4 4   1.615
Lotus Europa 30.4 4   1.513

In [33]:
subset(mtcars, mpg > 30 & mpg < 32, select=-c(mpg, cyl, wt))

disp hp  drat qsec  vs am gear carb
Honda Civic  75.7  52 4.93 18.52 1  1  4    2   
Lotus Europa 95.1 113 3.77 16.90 1  1  5    2

In [34]:
mtcars[mtcars$mpg>30, ]

mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Fiat 128       32.4 4   78.7  66 4.08 2.200 19.47 1  1  4    1   
Honda Civic    30.4 4   75.7  52 4.93 1.615 18.52 1  1  4    2   
Toyota Corolla 33.9 4   71.1  65 4.22 1.835 19.90 1  1  4    1   
Lotus Europa   30.4 4   95.1 113 3.77 1.513 16.90 1  1  5    2

In [38]:
library(readxl)
data <- read_xlsx("../mydata/일별평균대기오염도_2023.xlsx")
head(data)

측정일시 측정소명 이산화질소농도 오존농도 일산화탄소농도 아황산가스농도
1 20230101 강남구   0.0240         0.0240   0.60           0.0040        
2 20230101 강동구   0.0270         0.0170   0.70           0.0030        
3 20230101 강북구       NA         0.0260   0.70           0.0040        
4 20230101 강서구   0.0210         0.0250   0.60           0.0040        
5 20230101 관악구   0.0250         0.0200   0.60           0.0030        
6 20230101 광진구   0.0175         0.0176   0.79           0.0026        
  미세먼지농도 초미세먼지농도 월 일
1 52           36             01 01
2 56           43             01 01
3 51           34             01 01
4 62           38             01 01
5 54           35             01 01
6 48           36             01 01

In [40]:
tail(data)

측정일시 측정소명     이산화질소농도 오존농도 일산화탄소농도 아황산가스농도
1 20231231 항동         0.0251         0.0169   0.77           0.0028        
2 20231231 행주         0.0167         0.0257   0.68           0.0026        
3 20231231 마포아트센터 0.0266         0.0187   0.68           0.0029        
4 20231231 서울숲       0.0207         0.0159   0.91           0.0024        
5 20231231 올림픽공원   0.0245         0.0121   0.93           0.0024        
6 20231231 자연사박물관 0.0251         0.0199   0.89           0.0026        
  미세먼지농도 초미세먼지농도 월 일
1 21           17             12 31
2 25           16             12 31
3 26           20             12 31
4 23           16             12 31
5 19           18             12 31
6 19           15             12 31

In [44]:
print(apply(data[c(7,8)], 2, mean, na.rm=T))

  미세먼지농도 초미세먼지농도 
      38.43839       19.56359 


In [45]:
summary(data[c(3:8)])

 이산화질소농도      오존농도       일산화탄소농도   아황산가스농도   
 Min.   :0.0013   Min.   :0.00110   Min.   :0.0300   Min.   :0.00080  
 1st Qu.:0.0131   1st Qu.:0.01910   1st Qu.:0.3600   1st Qu.:0.00250  
 Median :0.0198   Median :0.02770   Median :0.4500   Median :0.00280  
 Mean   :0.0222   Mean   :0.02898   Mean   :0.4772   Mean   :0.00288  
 3rd Qu.:0.0292   3rd Qu.:0.03740   3rd Qu.:0.5600   3rd Qu.:0.00320  
 Max.   :0.0763   Max.   :0.10400   Max.   :1.4100   Max.   :0.00790  
 NA's   :91       NA's   :93        NA's   :484      NA's   :221      
  미세먼지농도    초미세먼지농도  
 Min.   :  3.00   Min.   :  1.00  
 1st Qu.: 22.00   1st Qu.: 11.00  
 Median : 32.00   Median : 17.00  
 Mean   : 38.44   Mean   : 19.56  
 3rd Qu.: 47.00   3rd Qu.: 25.00  
 Max.   :351.00   Max.   :116.00  
 NA's   :113      NA's   :118     

In [46]:
str(data)

tibble [18,250 × 10] (S3: tbl_df/tbl/data.frame)
 $ 측정일시      : num [1:18250] 20230101 20230101 20230101 20230101 20230101 ...
 $ 측정소명      : chr [1:18250] "강남구" "강동구" "강북구" "강서구" ...
 $ 이산화질소농도: num [1:18250] 0.024 0.027 NA 0.021 0.025 0.0175 0.019 0.023 0.031 0.02 ...
 $ 오존농도      : num [1:18250] 0.024 0.017 0.026 0.025 0.02 0.0176 0.021 0.024 0.022 0.029 ...
 $ 일산화탄소농도: num [1:18250] 0.6 0.7 0.7 0.6 0.6 0.79 0.4 0.6 0.7 0.7 ...
 $ 아황산가스농도: num [1:18250] 0.004 0.003 0.004 0.004 0.003 0.0026 0.003 0.004 0.004 0.003 ...
 $ 미세먼지농도  : num [1:18250] 52 56 51 62 54 48 53 47 51 43 ...
 $ 초미세먼지농도: num [1:18250] 36 43 34 38 35 36 35 38 39 32 ...
 $ 월            : chr [1:18250] "01" "01" "01" "01" ...
 $ 일            : chr [1:18250] "01" "01" "01" "01" ...


In [47]:
data$`월`

[1] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
   [15] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
   [29] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
   [43] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
   [57] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
   [71] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
   [85] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
   [99] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [113] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [127] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [141] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [155] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [169] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [183] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [197] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [211] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [225] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [239] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [253] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [267] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [281] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [295] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [309] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [323] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [337] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [351] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [365] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [379] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [393] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [407] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [421] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [435] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [449] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [463] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [477] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [491] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [505] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [519] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [533] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [547] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [561] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [575] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [589] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [603] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [617] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [631] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [645] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [659] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [673] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [687] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [701] "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01" "01"
  [715] "01" "01" "01" "01